version: "3.7"
services:
    micliente:
        image: "micliente:3.1"
        build: .
        restart: always
        environment:
            - REACT_APP_API_BACKEND=http://localhost:4000/apuesta/api/v1
            - REACT_APP_PATH=apuesta
            - REACT_APP_KEY=yzR64p2_MMHOrpSbZaoAIzaSyBqcIlr5p3rDL3o
        ports:
            - "9092:80"